### ISSUE TITLE
Error: Cannot find module 'escape-html'

### ISSUE THREAD

**Issue by regisd** [cataria-rocks/md2xliff#38]
Steps:
- `git clone --depth 1 --branch v2.0.0 https://github.com/cataria-rocks/md2xliff.git`
- `brew install nodejs`
- `./bin/extract myfile.md`

Expected:
Generates xliff file

Actual:

> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'escape-html'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)

**Comment by regisd** [comment]
This is just a documentation issue. Fixed with:
```
npm install escape-html
```

**Comment by tadatuta** [comment]
@regisd hi! have you tried to use code from `master` instead of `v2.0.0` release? it was quite 
 a huge refactoring.
