### ISSUE TITLE
punctuation characters like . and ! are extracted into the skeleton

### ISSUE THREAD

**Issue by timaschew** [cataria-rocks/md2xliff#5]
But they should be extracted into the XLIFF file instead.

**Comment by tadatuta** [comment]
@timaschew you are right, I'm working on new implementation right now, will fix this issue in following release

**Comment by timaschew** [comment]
cool, is it this one https://github.com/tadatuta/md2xliff/commit/f5d329f9f31e12322829dacad1a6a893f54df868 ?

**Comment by tadatuta** [comment]
nope, that'll be ground up rewrite of a module (but with compatible API)

**Comment by timaschew** [comment]
Why the string is splitted by these chars at all?
`text.split(/[;|\.|!|\?]\s/).forEach(onText);`

**Comment by tadatuta** [comment]
probability to find match for smaller segments in TM is much higher. but it will be tweakable via options in the future.

**Comment by tadatuta** [comment]
Fixed in https://github.com/tadatuta/md2xliff/commit/09cb1da834f2675b90fa6f1c8ee38394b57d5c42
